// QRVentana.cs
using System.Drawing;
using System.Windows.Forms;

public partial class QRVentana : Form
{
    private PictureBox pbQRCodeDisplay;
    private Button btnSaveQR; // Button to save the QR code

    public QRVentana(Bitmap qrCodeImage)
    {
        InitializeComponent(); // This method is generated by the designer

        this.Text = "Código QR del Vehículo"; // Changed title
        this.Size = new Size(300, 350); // Adjust size as needed
        this.FormBorderStyle = FormBorderStyle.FixedDialog; // Prevent resizing
        this.MaximizeBox = false;
        this.MinimizeBox = false;
        this.StartPosition = FormStartPosition.CenterParent; // Center relative to main form

        // PictureBox to display the QR code
        pbQRCodeDisplay = new PictureBox()
        {
            Location = new Point(25, 20), // Adjust position
            Size = new Size(250, 250),   // Adjust size
            BorderStyle = BorderStyle.FixedSingle,
            SizeMode = PictureBoxSizeMode.Zoom, // Zoom to fit
            Image = qrCodeImage // Assign the passed image
        };
        this.Controls.Add(pbQRCodeDisplay);

        // Button to save the QR code image
        btnSaveQR = new Button()
        {
            Text = "Guardar QR",
            Location = new Point(100, 280), // Adjust position
            Size = new Size(100, 30)
        };
        btnSaveQR.Click += BtnSaveQR_Click;
        this.Controls.Add(btnSaveQR);
    }

    // This method is usually generated by the designer.
    // If you created the file manually, you might need to add it or skip it
    // if you prefer to define all controls programmatically.
    private void InitializeComponent()
    {
        this.SuspendLayout();
        //
        // QRVentana
        //
        this.ClientSize = new System.Drawing.Size(284, 261); // Default size, will be overridden
        this.Name = "QRVentana";
        this.ResumeLayout(false);
    }

    private void BtnSaveQR_Click(object sender, System.EventArgs e)
    {
        if (pbQRCodeDisplay.Image != null)
        {
            using (SaveFileDialog sfd = new SaveFileDialog())
            {
                sfd.Filter = "PNG Image|*.png|Bitmap Image|*.bmp|JPEG Image|*.jpg";
                sfd.Title = "Guardar Código QR como Imagen";
                sfd.FileName = "qrcode_vehiculo.png"; // Default filename

                if (sfd.ShowDialog() == DialogResult.OK)
                {
                    pbQRCodeDisplay.Image.Save(sfd.FileName);
                    MessageBox.Show("QR Code guardado exitosamente.", "Guardado", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
        }
    }

    // Override OnFormClosed to dispose the image when the form is closed
    protected override void OnFormClosed(FormClosedEventArgs e)
    {
        base.OnFormClosed(e);
        if (pbQRCodeDisplay.Image != null)
        {
            pbQRCodeDisplay.Image.Dispose();
            pbQRCodeDisplay.Image = null;
        }
    }
}